package Hibernatepkg;
// Generated 2016-12-26 11:39:12 by Hibernate Tools 4.3.1



/**
 * Admintable generated by hbm2java
 */
public class Admintable  implements java.io.Serializable {


     private String name;
     private String password1;
     private String password2;

    public Admintable() {
    }

	
    public Admintable(String name) {
        this.name = name;
    }
    public Admintable(String name, String password1, String password2) {
       this.name = name;
       this.password1 = password1;
       this.password2 = password2;
    }
   
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword1() {
        return this.password1;
    }
    
    public void setPassword1(String password1) {
        this.password1 = password1;
    }
    public String getPassword2() {
        return this.password2;
    }
    
    public void setPassword2(String password2) {
        this.password2 = password2;
    }




}


