package Hibernatepkg;
// Generated 2016-12-26 11:39:12 by Hibernate Tools 4.3.1



/**
 * Jobtable generated by hbm2java
 */
public class Jobtable  implements java.io.Serializable {


     private String jobId;
     private String NVacancies;
     private String location;
     private String skillsRequired;
     private String dateInterview;
     private String whomContact;
     private String email;

    public Jobtable() {
    }

	
    public Jobtable(String jobId) {
        this.jobId = jobId;
    }
    public Jobtable(String jobId, String NVacancies, String location, String skillsRequired, String dateInterview, String whomContact, String email) {
       this.jobId = jobId;
       this.NVacancies = NVacancies;
       this.location = location;
       this.skillsRequired = skillsRequired;
       this.dateInterview = dateInterview;
       this.whomContact = whomContact;
       this.email = email;
    }
   
    public String getJobId() {
        return this.jobId;
    }
    
    public void setJobId(String jobId) {
        this.jobId = jobId;
    }
    public String getNVacancies() {
        return this.NVacancies;
    }
    
    public void setNVacancies(String NVacancies) {
        this.NVacancies = NVacancies;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getSkillsRequired() {
        return this.skillsRequired;
    }
    
    public void setSkillsRequired(String skillsRequired) {
        this.skillsRequired = skillsRequired;
    }
    public String getDateInterview() {
        return this.dateInterview;
    }
    
    public void setDateInterview(String dateInterview) {
        this.dateInterview = dateInterview;
    }
    public String getWhomContact() {
        return this.whomContact;
    }
    
    public void setWhomContact(String whomContact) {
        this.whomContact = whomContact;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


