package newreflect;
// Generated 2016-12-26 11:39:12 by Hibernate Tools 4.3.1



/**
 * UserInf generated by hbm2java
 */
public class UserInf  implements java.io.Serializable {


     private String id;
     private String name;
     private String phone;
     private Character gender;
     private Integer age;
     private String password;
     private String passcheck;
     private String qualification;
     private Boolean java;
     private Boolean cplus;
     private Boolean javaweb;
     private String photopath;
     private String expirence;
     private String address;

    public UserInf() {
    }

	
    public UserInf(String id) {
        this.id = id;
    }
    public UserInf(String id, String name, String phone, Character gender, Integer age, String password, String passcheck, String qualification, Boolean java, Boolean cplus, Boolean javaweb, String photopath, String expirence, String address) {
       this.id = id;
       this.name = name;
       this.phone = phone;
       this.gender = gender;
       this.age = age;
       this.password = password;
       this.passcheck = passcheck;
       this.qualification = qualification;
       this.java = java;
       this.cplus = cplus;
       this.javaweb = javaweb;
       this.photopath = photopath;
       this.expirence = expirence;
       this.address = address;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPasscheck() {
        return this.passcheck;
    }
    
    public void setPasscheck(String passcheck) {
        this.passcheck = passcheck;
    }
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }
    public Boolean getJava() {
        return this.java;
    }
    
    public void setJava(Boolean java) {
        this.java = java;
    }
    public Boolean getCplus() {
        return this.cplus;
    }
    
    public void setCplus(Boolean cplus) {
        this.cplus = cplus;
    }
    public Boolean getJavaweb() {
        return this.javaweb;
    }
    
    public void setJavaweb(Boolean javaweb) {
        this.javaweb = javaweb;
    }
    public String getPhotopath() {
        return this.photopath;
    }
    
    public void setPhotopath(String photopath) {
        this.photopath = photopath;
    }
    public String getExpirence() {
        return this.expirence;
    }
    
    public void setExpirence(String expirence) {
        this.expirence = expirence;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


